In [1]:
import duckdb

con = duckdb.connect("warehouse.duckdb")

In [5]:
con.sql("""
select
  date_diff('hour', event_time, _ingested_at) as do_tre_gio,
  count(*) as so_event
from bronze_events
group by 1
order by 1
""").df()

    do_tre_gio  so_event
0            0     10470
1            1     21156
2            2     21194
3            3     20869
4            4     21022
5            5     20961
6            6      7251
7           43        77
8           44       218
9           45       213
10          46       221
11          47       254
12          48       252
13          49       238
14          50       224
15          51       222
16          52       222
17          53       223
18          54       240
19          55       234
20          56       244
21          57       233
22          58       260
23          59       257
24          60       253
25          61       236
26          62       221
27          63       229
28          64       247
29          65       240
30          66       252
31          67       230
32          68       252
33          69       246
34          70       237
35          71        64

In [6]:
con.sql("""
select
  quantile_cont(date_diff('second', event_time, _ingested_at)/86400.0, 0.50) as p50_ngay,
  quantile_cont(date_diff('second', event_time, _ingested_at)/86400.0, 0.95) as p95_ngay,
  quantile_cont(date_diff('second', event_time, _ingested_at)/86400.0, 0.99) as p99_ngay,
  max(date_diff('second', event_time, _ingested_at)/86400.0) as max_ngay,
  avg(case when _ingested_at > event_time + interval 1 day then 1.0 else 0 end) as ty_le_late
from bronze_events
""").df()

   p50_ngay  p95_ngay  p99_ngay  max_ngay  ty_le_late
0   0.12809  1.813693  2.725833  2.944688    0.050509